### ISSUE TITLE
serverTimestamp *intermittently* available in ms.MessagingEventNotification response

### ISSUE THREAD

**Issue by cjames1224** [LivePersonInc/node-agent-sdk#35]
The serverTimestamp property is only intermittently available in ms.MessagingEventNotification response. For code that requires the serverTimestamp, this is problematic. Is this expected behavior?

**Comment by donmanguno** [comment]
Hi Christian,
According to my tests the serverTimestamp is not present on any ms.MessagingEventNotifications of type ChatStateEvent, but is present consistently for other event types. Are these your findings as well? If not please give some more details about the types of events that are lacking this property.

I see that the documentation does list this as a required parameter of the response, so I am reaching out to the owner of this system to determine the expected behavior and update the documentation accordingly.

**Comment by cjames1224** [comment]
Thank you, Mark.
Yes you are correct, we are not seeing the serverTimestamp on
ChatStateEvent responses. And also, as you've stated, the expectation was
that it is a required parameter of the response.

**Comment by donmanguno** [comment]
Hi Christian,

I have received confirmation that the ChatStateEvent lacks a timestamp by design, and it is the only such event. I will work to ensure that the documentation is updated accordingly.

**Comment by cjames1224** [comment]
Understood, thanks Mark. Can close this issue when ready.
